{{ config(materialized='table') }}


SELECT          
    MD5(LOWER(TRIM(Player)) || Squad || Nation) AS gk_id,
    Player                      AS gk,
    Nation                      AS nation,
    Squad                       AS club,
    Age                         AS age,
    MP                          AS mp,
    Starts                      AS starts,
    Min                         AS min,
    "90s"                       AS nineties,
    Ast                         AS assists,
    "G+A"                       AS goals_plus_assists,
    CrdY                        AS yellow_cards,
    CrdR                        AS red_cards,
    xG                          AS xg,
    npxG                        AS npxg,
    xAG                         AS xag,
    "npxG+xAG"                  AS npxg_plus_xag,
    "G+A-PK"                    AS ga_minus_pk,
    "xG+xAG"                    AS xg_plus_xag,
    PrgC                        AS progressive_carries,
    PrgP                        AS progressive_passes,
    Sh                          AS shots,
    "Sh/90"                     AS shots_per_90,
    xG_stats_shooting           AS xg_stats_shooting,
    npxG_stats_shooting         AS npxg_stats_shooting,
    "G-xG"                      AS g_minus_xg,
    "np:G-xG"                   AS npxg_minus_xg,
    Cmp                         AS passes_completed,
    Att                         AS passes_attempted,
    "Cmp%"                      AS pass_completion_pct,
    TotDist                     AS total_distance,
    PrgDist                     AS progressive_distance,
    Ast_stats_passing           AS assists_passing_stats,
    xAG_stats_passing           AS xag_stats_passing,
    xA                          AS xa,
    "A-xAG"                     AS a_minus_xag,
    KP                          AS key_passes,
    "1/3"                       AS final_third_passes,
    PPA                         AS passes_into_penalty_area,
    PrgP_stats_passing          AS progressive_passes_passing_stats,
    Live                        AS live_passes,
    Dead                        AS dead_passes,
    FK_stats_passing_types      AS free_kick_passes,
    TB                          AS through_balls,
    Sw                          AS switches,
    Cmp_stats_passing_types     AS completed_passes_passing_types,
    Tkl                         AS tackles,
    TklW                        AS tackles_won,
    "Def 3rd"                   AS defensive_third_tackles,
    Att_stats_defense           AS defensive_actions_attempted,
    Lost                        AS lost_tackles,
    Blocks_stats_defense        AS blocks,
    Pass                        AS pass_blocks,
    "Int"                         AS interceptions,
    "Tkl+Int"                   AS tackles_plus_interceptions,
    Clr                         AS clearances,
    Err                         AS errors,
    SCA                         AS shot_creating_actions,
    SCA90                       AS sca_per_90,
    PassLive                    AS shot_creating_live_passes,
    PassDead                    AS shot_creating_dead_passes,
    GCA                         AS goal_creating_actions,
    GCA90                       AS gca_per_90,
    Touches                     AS touches,
    "Def Pen"                   AS defensive_penalty_area_touches,
    "Def 3rd_stats_possession"    AS defensive_third_possession,
    "Mid 3rd_stats_possession"    AS midfield_third_possession,
    "Att 3rd_stats_possession"    AS attacking_third_possession,
    "Att Pen"                     AS attacking_penalty_area_touches,
    Live_stats_possession       AS live_ball_possessions,
    Att_stats_possession        AS attacking_touches_possession,
    Succ                        AS dribbles_successful,
    Tkld                        AS dribbles_tackled,
    Carries                     AS carries,
    TotDist_stats_possession    AS carries_total_distance,
    PrgDist_stats_possession    AS carries_progressive_distance,
    PrgC_stats_possession       AS progressive_carries_stats,
    "1/3_stats_possession"      AS carries_into_final_third,
    CPA                         AS carries_into_penalty_area,
    Mis                         AS miscontrols,
    Dis                         AS dispossessed,
    Rec                         AS receptions,
    CrdY_stats_misc             AS yellow_cards_misc,
    CrdR_stats_misc             AS red_cards_misc,
    Fls                         AS fouls,
    Fld_stats_misc              AS fouled,
    Int_stats_misc              AS interceptions_misc,
    TklW_stats_misc             AS tackles_won_misc,
    PKcon                       AS penalties_conceded,
    OG                          AS own_goals,
    Recov                       AS recoveries,
    Won                         AS duels_won,
    Lost_stats_misc             AS duels_lost,
    "Won%"                     AS duels_win_pct,
    GA                          AS goals_allowed,
    GA90                        AS goals_allowed_per_90,
    SoTA                        AS shots_on_target_against,
    Saves                       AS saves,
    "Save%"                    AS save_pct,
    W                           AS wins,
    D                           AS draws,
    L                           AS losses,
    CS                          AS clean_sheets,
    "CS%"                      AS clean_sheet_pct,
    PKatt_stats_keeper          AS pk_attempts_faced,
    PKA                         AS pk_allowed,
    PKsv                        AS pk_saved,
    PSxG                        AS post_shot_xg,
    "PSxG/SoT"                  AS psxg_per_shot_on_target,
    "PSxG+/-"                   AS psxg_plus_minus,
    "/90"                       AS psxg_per_90,
    Cmp_stats_keeper_adv        AS keeper_passes_completed,
    Att_stats_keeper_adv        AS keeper_passes_attempted,
    "Cmp%_stats_keeper_adv"     AS keeper_pass_completion_pct,
    "Att (GK)"                  AS keeper_att,
    Thr                         AS throws,
    "Launch%"                   AS launch_pct,
    AvgLen                      AS average_pass_length,
    Opp                         AS opponents_faced,
    Stp                         AS keeper_stops,
    "Stp%"                      AS keeper_stop_pct,
    "#OPA"                      AS sweeper_actions,
    "#OPA/90"                   AS sweeper_actions_per_90,
    AvgDist                     AS average_sweeper_distance

FROM {{ ref('cleaned_gk') }}