
{{ config(materialized='table') }}

SELECT
    
    club_name AS club,
    club_url AS club_url,
    Pts AS points,
    "Games Played" AS games_played,
    Goals AS goals,
    "Goals Conceded" AS goals_conceded,
    XG AS xg,
    Shots AS shots,
    "Shots On Target" AS shots_on_target,
    "Shots On Target Inside the Box" AS shots_on_target_inside_box,
    "Shots On Target Outside the Box" AS shots_on_target_outside_box,
    "Touches in the Opposition Box" AS touches_opposition_box,
    penalties AS penalties,
    penalties_scored AS penalties_scored,
    "Free Kicks Scored" AS free_kicks_scored,
    "Hit Woodwork" AS hit_woodwork,
    crosses AS crosses,
    cross_accuracy AS cross_accuracy,
    Interceptions AS interceptions,
    Blocks AS blocks,
    Clearances AS clearances,
    Passes AS passes,
    long_passes AS long_passes,
    long_pass_accuracy AS long_pass_accuracy,
    "Corners Taken" AS corners_taken,
    dribble_attempts AS dribble_attempts,
    dribble_accuracy AS dribble_accuracy,
    "Duels Won" AS duels_won,
    "Aerial Duels Won" AS aerial_duels_won,
    "Red Cards" AS red_cards,
    "Yellow Cards" AS yellow_cards,
    Fouls AS fouls,
    Offsides AS offsides,
    "Own Goals" AS own_goals,
    penalties_saved AS penalties_saved,
    penalty_save_precentage AS penalty_save_percentage,
    free_kicks_taken AS free_kicks_taken,
    free_kicks_scored AS free_kicks_scored,
    "Penalties Taken" AS penalties_taken
FROM {{ ref('cleaned_club') }}