{{ config(materialized='table') }}

SELECT
    d.club_id,
    c.points,
    c.games_played,
    c.goals,
    c.goals_conceded,
    c.xg,
    c.shots,
    c.shots_on_target,
    c.shots_on_target_inside_box,
    c.shots_on_target_outside_box,
    c.touches_opposition_box,
    c.penalties,
    c.penalties_scored,
    c.free_kicks_scored,
    c.hit_woodwork,
    c.crosses,
    c.cross_accuracy,
    c.interceptions,
    c.blocks,
    c.clearances,
    c.passes,
    c.long_passes,
    c.long_pass_accuracy,
    c.corners_taken,
    c.dribble_attempts,
    c.dribble_accuracy,
    c.duels_won,
    c.aerial_duels_won,
    c.red_cards,
    c.yellow_cards,
    c.fouls,
    c.offsides,
    c.own_goals,
    c.penalties_saved,
    c.penalty_save_percentage,
    c.free_kicks_taken,
    c.free_kicks_scored,
    c.penalties_taken
FROM {{ ref('stg_club') }} c
LEFT JOIN {{ ref('dim_club') }} d
    ON LOWER(TRIM(c.club)) = LOWER(TRIM(d.club))
